# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9414aaee69035bf499d7fc9aeb73092be49290952600f4f385bedf677273437a264459756fa45632c259d0551e516c67b274fcf6f164bee9f56a62d2f47afd36

test:
  secret_key_base: abdbb6b228abe796e857bdfc7d19c1108124eebf486abc788b66850d5ea2b09ff9c429217dd8eb12a46df521bcdf6b6cb603ac2ad8d361d0771245c2af96b3bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
